/*
Purpose: Registry declaring resume template metadata (layouts, Pro lock flags) and custom font settings.
Used By: ResumeEditor.jsx, Dashboard.jsx, Dashboard templates dialog
Request Flow: Frontend Editor loading -> Read configurations -> Render layout panels
Data Flow: Static metadata lookup configurations -> Editor layout engine
Learn: Static registries, configuration constants, typography pairing rules
*/
export const TEMPLATE_CONFIGS = {
  template1: {
    id: "template1",
    name: "Professional Classic",
    category: "Professional",
    layout: "single-column",
    headerStyle: "classic",
    hasSidebar: false,
    isPro: false,
    description: "Traditional corporate layout with balanced margins and high readability. Best for standard business and office roles.",
    bestUseCase: "Corporate, Legal, Finance, Administrative",
    personality: "Traditional, Balanced, Trusted",
    defaults: { fontPairing: "inter" }
  },
  template2: {
    id: "template2",
    name: "Nova Columns",
    category: "Modern",
    layout: "sidebar-left",
    headerStyle: "sidebar",
    hasSidebar: true,
    sidebarSections: ["skills", "languages", "interests", "technicalProfiles"],
    isPro: true,
    description: "Two-column layout with a left sidebar for skills and contact links. Keeps core experience highlighted on the right.",
    bestUseCase: "Product Management, Marketing, Design",
    personality: "Creative, Dynamic, Structured",
    defaults: { fontPairing: "outfit" }
  },
  template3: {
    id: "template3",
    name: "Horizon Premium",
    category: "Modern",
    layout: "single-column",
    headerStyle: "bleed",
    hasSidebar: false,
    isPro: true,
    description: "Bold horizontal top header block for contact information, followed by a clean full-width single-column body.",
    bestUseCase: "Engineering, Sales, Media",
    personality: "Confident, Modern, Clean",
    defaults: { fontPairing: "jakarta" }
  },
  premium1: {
    id: "premium1",
    name: "Prestige Timeline",
    category: "Executive",
    layout: "single-column",
    headerStyle: "classic",
    hasSidebar: false,
    isPro: true,
    description: "Elegantly formats professional experience with a left-aligned vertical line/dot timeline layout. Highly visual.",
    bestUseCase: "Directors, Senior Managers, Consultants",
    personality: "Linear, Progressive, Distinguished",
    defaults: { fontPairing: "cormorant" }
  },
  premium2: {
    id: "premium2",
    name: "Executive Bold",
    category: "Executive",
    layout: "single-column",
    headerStyle: "executive",
    hasSidebar: false,
    isPro: true,
    description: "Striking bold horizontal styling and strong heading text weight designed to command attention from recruiters.",
    bestUseCase: "CEOs, Directors, Executive Leaders",
    personality: "Commanding, Traditional, Stately",
    defaults: { fontPairing: "tinos" }
  },
  premium3: {
    id: "premium3",
    name: "Elite Compact",
    category: "Compact",
    layout: "sidebar-right",
    headerStyle: "compact",
    hasSidebar: true,
    sidebarSections: ["skills", "languages", "interests", "technicalProfiles"],
    isPro: true,
    description: "Optimized for dense content, packing maximum details into a single page with high readability and tight line heights.",
    bestUseCase: "Technicians, Early-career Engineers, High-density CVs",
    personality: "Efficient, Organized, Direct",
    defaults: { fontPairing: "inter" }
  },
  premium4: {
    id: "premium4",
    name: "Signature Minimal",
    category: "Modern",
    layout: "single-column",
    headerStyle: "sig",
    hasSidebar: false,
    isPro: true,
    description: "Refined minimalist aesthetic featuring subtle divider lines, small headers, and a polished contemporary rhythm.",
    bestUseCase: "Creatives, Architects, Tech Leads",
    personality: "Aesthetic, Understated, Premium",
    defaults: { fontPairing: "playfair" }
  },
  premium5: {
    id: "premium5",
    name: "Apex Accent",
    category: "Modern",
    layout: "single-column",
    headerStyle: "accentbar",
    hasSidebar: false,
    isPro: true,
    description: "Clean layouts with subtle color accents and solid horizontal rules to demarcate major career milestones.",
    bestUseCase: "Sales, Business Development, Project Managers",
    personality: "Vibrant, Energetic, Direct",
    defaults: { fontPairing: "raleway" }
  },
  premium6: {
    id: "premium6",
    name: "Nova Split",
    category: "Modern",
    layout: "sidebar-left",
    headerStyle: "sidebar",
    hasSidebar: true,
    sidebarSections: ["skills", "languages", "interests", "technicalProfiles"],
    isPro: true,
    description: "Sophisticated side-column design featuring a dark sidebar for contact coordinates and skills, and a light background for core content.",
    bestUseCase: "UI/UX Designers, Developers, Designers",
    personality: "Contrast-rich, Modern, Visual",
    defaults: { fontPairing: "jakarta" }
  },
  premium7: {
    id: "premium7",
    name: "Modern Block",
    category: "Modern",
    layout: "single-column",
    headerStyle: "classic",
    hasSidebar: false,
    isPro: true,
    description: "Sections are organized into visual card blocks for clean semantic separation, ideal for modern digital industries.",
    bestUseCase: "Startups, Growth Marketing, Creative Tech",
    personality: "Blocky, Solid, Organized",
    defaults: { fontPairing: "sora" }
  },
  premium8: {
    id: "premium8",
    name: "Visual Portfolio",
    category: "Modern",
    layout: "sidebar-left",
    headerStyle: "sidebar",
    hasSidebar: true,
    sidebarSections: ["skills", "languages", "interests", "technicalProfiles"],
    isPro: true,
    description: "Incorporates a graphic infographic-inspired sidebar, perfect for showing project categories and visual skill distributions.",
    bestUseCase: "Graphic Designers, Content Creators, Artists",
    personality: "Visual, Graphic, Articulate",
    defaults: { fontPairing: "raleway" }
  },
  premium9: {
    id: "premium9",
    name: "Prestige Centered",
    category: "Executive",
    layout: "single-column",
    headerStyle: "centered",
    hasSidebar: false,
    isPro: true,
    description: "Centered name and contact links with full-width section headers, conveying a clean and traditional prestige feel.",
    bestUseCase: "Consultants, Academic Directors, Senior Advisors",
    personality: "Traditional, Centered, Elegant",
    defaults: { fontPairing: "cormorant" }
  },
  premium10: {
    id: "premium10",
    name: "Minimalist Developer",
    category: "Compact",
    layout: "single-column",
    headerStyle: "tech",
    hasSidebar: false,
    isPro: true,
    description: "Compact and technical developer-oriented layout using monospaced subtitle hints and high-density listings.",
    bestUseCase: "Software Engineers, System Admins, Data Scientists",
    personality: "Technical, Clean, Functional",
    defaults: { fontPairing: "sourcecode" }
  },
  ats_classic: {
    id: "ats_classic",
    name: "ATS Standard",
    category: "ATS Optimized",
    layout: "single-column",
    headerStyle: "ats-classic",
    hasSidebar: false,
    isPro: true,
    description: "Fully optimized single-column layout with 100% linear DOM structure, designed to pass the most strict parser bots.",
    bestUseCase: "Standard ATS screening, High-volume job applications",
    personality: "ATS-Safe, Linear, High-scan",
    defaults: { fontPairing: "inter" }
  },
  ats_entry: {
    id: "ats_entry",
    name: "ATS Professional",
    category: "ATS Optimized",
    layout: "sidebar-left",
    headerStyle: "ats-entry-header",
    hasSidebar: true,
    sidebarSections: ["skills", "languages", "interests", "technicalProfiles"],
    isPro: true,
    description: "ATS-compliant layout featuring two columns of text that fold dynamically for maximum readability in human review.",
    bestUseCase: "Associate and Senior Software Engineers",
    personality: "ATS-Optimized, Balanced, Modern",
    defaults: { fontPairing: "inter" }
  },
  ats_senior: {
    id: "ats_senior",
    name: "Scholar ATS",
    category: "ATS Optimized",
    layout: "single-column",
    headerStyle: "ats-classic-serif",
    hasSidebar: false,
    isPro: true,
    description: "ATS-safe layout using premium serif typography, conveying traditional seniority and high-level academic credentials.",
    bestUseCase: "Researchers, Professors, Senior Advisors",
    personality: "Academic, Traditional, ATS-Intelligent",
    defaults: { fontPairing: "lora" }
  },
  ats_lead: {
    id: "ats_lead",
    name: "Executive ATS",
    category: "ATS Optimized",
    layout: "single-column",
    headerStyle: "ats-entry-header",
    hasSidebar: false,
    isPro: true,
    description: "Sleek and professional single-column ATS layout with expanded summary and metric highlighting blocks.",
    bestUseCase: "Product Owners, Leads, Executive Managers",
    personality: "Metrics-focused, Executive, High-scan",
    defaults: { fontPairing: "inter" }
  },
  ats_intern: {
    id: "ats_intern",
    name: "Entry ATS",
    category: "ATS Optimized",
    layout: "single-column",
    headerStyle: "ats-classic",
    hasSidebar: false,
    isPro: true,
    description: "ATS-safe format that bubbles Education and Projects to the top, designed for students and fresh graduates.",
    bestUseCase: "Internships, University Recruiting, Career Changers",
    personality: "Projects-first, Academic, Clean",
    defaults: { fontPairing: "inter" }
  },
  ats_experienced: {
    id: "ats_experienced",
    name: "Corporate ATS",
    category: "ATS Optimized",
    layout: "sidebar-left",
    headerStyle: "ats-entry-header",
    hasSidebar: true,
    sidebarSections: ["skills", "languages", "interests", "technicalProfiles"],
    isPro: true,
    description: "A crisp corporate format optimized for both parsing engines and quick human scanning, prioritizing work experience.",
    bestUseCase: "Mid-level and Senior Professionals",
    personality: "Experience-first, Structured, Corporate",
    defaults: { fontPairing: "inter" }
  },
  academic_cv: {
    id: "academic_cv",
    name: "Research Scholar",
    category: "Academic",
    layout: "single-column",
    headerStyle: "centered-academic",
    hasSidebar: false,
    isPro: true,
    description: "The premier full-width academic CV template. Specially typeset for bibliography publications, citations, and awards.",
    bestUseCase: "PhD Students, Academic Researchers, Postdocs",
    personality: "Academic, Citation-first, Scholarly",
    defaults: { fontPairing: "lora" }
  }
};

export const FONT_REGISTRY = {
  inter: { id: "inter", label: "Corporate Sans (Inter)", desc: "Modern, high-contrast, optimal for ATS scanners" },
  sora: { id: "sora", label: "Modern Sans (Sora)", desc: "Contemporary, aesthetic, geometric headings" },
  playfair: { id: "playfair", label: "Signature Serif (Playfair)", desc: "Bold, elegant, high-impact branding" },
  outfit: { id: "outfit", label: "Minimal Sans (Outfit)", desc: "Clean, geometric, contemporary minimalist feel" },
  cormorant: { id: "cormorant", label: "Editorial Serif (Cormorant)", desc: "Refined, sophisticated, elegant headings" },
  spacegrotesk: { id: "spacegrotesk", label: "Tech Sans (Space Grotesk)", desc: "Sharp, technical, modern developer aesthetic" },
  raleway: { id: "raleway", label: "Contemporary Sans (Raleway)", desc: "Refined, high-legibility geometric styling" },
  jakarta: { id: "jakarta", label: "Modern Sans (Plus Jakarta)", desc: "Elegant, clean contemporary geometric" },
  ibmplex: { id: "ibmplex", label: "Tech Sans (IBM Plex)", desc: "Balanced, highly readable technical sans" },
  bodoni: { id: "bodoni", label: "Prestige Serif (Bodoni)", desc: "Luxury, high-contrast serif for senior advisors" },
  nunito: { id: "nunito", label: "Rounded Sans (Nunito)", desc: "Friendly, approachable rounded sans" },
  fraunces: { id: "fraunces", label: "Vintage Serif (Fraunces)", desc: "Editorial, expressive vintage layout" },
  sourcecode: { id: "sourcecode", label: "Developer Mono (Source Code)", desc: "Clean monospace font for tech details" },
  tinos: { id: "tinos", label: "Executive Serif (Tinos)", desc: "Professional, classic Times style for traditional roles" },
  lora: { id: "lora", label: "Academic Serif (Lora)", desc: "Traditional, academic, highly legible in print" }
};
